/**
 * AI-GENERATED MARKET EVENT TESTS
 * 
 * Tests that market events are generated by AI (not hardcoded),
 * integrate with threads, and reflect game state.
 */

import { test, expect } from '@playwright/test';

test.describe('AI Market Events', () => {
  
  test('market event prompt includes game state', async ({ page }) => {
    await page.goto('house-of-tide.html');
    
    // Start a new game
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'TestHouse');
    await page.fill('#input-founder', 'TestFounder');
    await page.click('text=Open the Ledger');
    
    // Skip onboarding
    await page.click('text=Skip →');
    
    // Advance to trading phase
    await page.click('text=Continue →'); // Complete house event
    await page.click('text=Continue →'); // Complete routes event
    
    // Wait for trading panel
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Check that market prices are displayed
    const saltFishPrice = await page.locator('text=Salt Fish').textContent();
    expect(saltFishPrice).toContain('Buy:');
    expect(saltFishPrice).toContain('Sell:');
  });
  
  test('market event can create thread', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'ThreadTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to trading
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Check for thread tracker (may or may not have threads)
    const threadTracker = await page.locator('#thread-tracker').isVisible();
    
    // If event created a thread, it should appear in tracker
    if (threadTracker) {
      const threadCount = await page.locator('#thread-count').textContent();
      expect(parseInt(threadCount)).toBeGreaterThanOrEqual(0);
    }
  });
  
  test('event narrative displays in trading panel', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'NarrativeTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to trading
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Check for season note (which contains event narrative if active)
    const seasonNote = await page.locator('#trading-season-note').textContent();
    expect(seasonNote.length).toBeGreaterThan(0);
  });
  
  test('price trend arrows show when prices change', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'TrendTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // First trading phase
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Complete trading phase
    await page.click('text=Close the Books →');
    
    // Next year - advance through house and routes
    await page.click('text=Turn the Page →');
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Price trends should be visible (↑↓→)
    const trendArrows = await page.locator('.price-trend').count();
    expect(trendArrows).toBeGreaterThan(0);
  });
  
  test('max buy button purchases maximum affordable', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'MaxBuyTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to trading
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Get initial marks
    const initialMarksText = await page.locator('#stat-marks').textContent();
    const initialMarks = parseInt(initialMarksText.replace(/[^0-9]/g, ''));
    
    // Click Max Buy for first commodity
    await page.click('.trading-btn.bulk >> text=Max Buy');
    
    // Marks should decrease
    const finalMarksText = await page.locator('#stat-marks').textContent();
    const finalMarks = parseInt(finalMarksText.replace(/[^0-9]/g, ''));
    expect(finalMarks).toBeLessThan(initialMarks);
    
    // Cargo should increase
    const capacityText = await page.locator('#trading-capacity').textContent();
    expect(capacityText).toMatch(/\d+ \/ \d+ units/);
  });
  
  test('sell all button sells entire stock', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'SellAllTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // First trading phase - buy something
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Buy max of first commodity
    await page.click('.trading-btn.bulk >> text=Max Buy');
    
    // Get stock level
    const stockText = await page.locator('.trading-stock').first().textContent();
    const stockMatch = stockText.match(/Stock:\s*(\d+)/);
    const initialStock = stockMatch ? parseInt(stockMatch[1]) : 0;
    expect(initialStock).toBeGreaterThan(0);
    
    // Click Sell All
    await page.click('.trading-btn.sell.bulk >> text=Sell All');
    
    // Stock should be 0
    const finalStockText = await page.locator('.trading-stock').first().textContent();
    expect(finalStockText).toContain('Stock: 0');
  });
  
  test('profit margin displays correctly', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'ProfitTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to trading
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Buy some cargo
    await page.click('.trading-btn.bulk >> text=Max Buy');
    
    // Margin should display
    const margins = await page.locator('.trading-margin').count();
    expect(margins).toBeGreaterThan(0);
    
    // Margin should have profit or loss class
    const marginClass = await page.locator('.trading-margin').first().getAttribute('class');
    expect(marginClass).toMatch(/profit|loss/);
  });
  
  test('cost basis tracks purchase price', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'BasisTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to trading
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Buy cargo
    await page.click('.trading-btn.bulk >> text=Max Buy');
    
    // Stock should show "Paid: X mk"
    const stockText = await page.locator('.trading-stock').first().textContent();
    expect(stockText).toContain('Paid:');
  });
  
  test('vs You shows profit/loss vs purchase price', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'VsYouTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // First trading - buy
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    await page.click('.trading-btn.bulk >> text=Max Buy');
    await page.click('text=Close the Books →');
    
    // Next year - sell
    await page.click('text=Turn the Page →');
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Margin should show "vs You: +/-X"
    const marginText = await page.locator('.trading-margin').first().textContent();
    expect(marginText).toContain('vs You:');
  });
  
  test('tutorial hint shows for first-time traders', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'TutorialTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // Advance to first trading phase
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Tutorial hint should be visible
    const hintVisible = await page.locator('.trading-hint').isVisible();
    expect(hintVisible).toBe(true);
    
    // Hint should mention Max Buy or Sell All
    const hintText = await page.locator('.trading-hint').textContent();
    expect(hintText).toMatch(/Max Buy|Sell All/i);
  });
  
  test('no tutorial hint for experienced traders', async ({ page }) => {
    await page.goto('http://localhost:3000/house-of-tide.html');
    await page.click('text=Begin the Founding');
    await page.fill('#input-dynasty', 'ExperiencedTest');
    await page.fill('#input-founder', 'Founder');
    await page.click('text=Open the Ledger');
    await page.click('text=Skip →');
    
    // First trading - make a trade
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    await page.click('.trading-btn.bulk >> text=Max Buy');
    await page.click('text=Close the Books →');
    
    // Next year
    await page.click('text=Turn the Page →');
    await page.click('text=Continue →');
    await page.click('text=Continue →');
    await page.waitForSelector('#panel-trading', { state: 'visible' });
    
    // Tutorial hint should NOT be visible (already traded before)
    const hintVisible = await page.locator('.trading-hint').isVisible();
    expect(hintVisible).toBe(false);
  });
});
